### ISSUE TITLE
We need to build a wall around the natives

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#11]

**Comment by DavidPH** [comment]
To make this issue useful: I do need to come up with some nice API for doing callbacks. Would also be good to establish a good convention to registering callbacks like pre-render and post-render.

**Comment by marrub--** [comment]
I believe this has been resolved, however I still feel it could be improved.

**Comment by DavidPH** [comment]
I think the macro for defining natives is solid, unless you have specific issues.

I do want to add a `Code::Callback` class with a call operator for making it stupid easy to make registerable callbacks. This would include adding an extra (probably repeatable) field to function blocks in the bytecode to register with said callbacks. It would also likely result in a single `DGE_RegisterCallback` function that takes a string index and function pointer. The only downside would be that it would take a `void (*)(void) [[call("StkCall"]]` pointer in C, requiring casting to register functions taking arguments. (A typedef would probably be provided in the header.)

Doing callbacks that way would *also* require changes to GDCC, but I mostly know what I want to do there, so I think it would be OK.

**Comment by marrub--** [comment]
I like how that is literally the exact detail of what you implemented and now I can close this
