### ISSUE TITLE
Per-point color for basic form rendering

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#12]
This may not be implementable on most of the drawing functions, but should be implemented with alternative functions at some point.
For circles, it may be possible to do this with a shader, very carefully. Any immediate mode functions will Just Work.

**Comment by Kyle873** [comment]
I'd really like to push for this to be available on as many drawing primitives as possible, even if it's necessary to use internal shaders to do so if other implementations aren't practical.

**Comment by marrub--** [comment]
This can be done with shaders actually, no need for native support
