### ISSUE TITLE
Sound rendering

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#22]
Need to consider sound engines to use, or we could roll our own (and possibly go insane doing so).
libvorbisfile/libvorbis/libogg seem to be pretty good, so those will probably be candidates for file decoders.

**Comment by Kyle873** [comment]
FMOD is definitely out, @DavidPH absolutely hates it and it has extremely restrictive licensing. Ditto for things such as BASS as it also has restrictive licensing IIRC. In the end we'll probably need to use a combination of OpenAL and a module handling library as well as libogg/libvorbis.

**Comment by marrub--** [comment]
Done with basic sound rendering, stuff like library support can be split into other issues.
