### ISSUE TITLE
VM debugging

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#27]
There's something that is a very big issue in ZDoom: There is no real way to debug scripts.
I think the reason this is an issue is obvious, so my question is, how should we handle this in DGE?

**Comment by marrub--** [comment]
Discussed elsewhere, closing

**Comment by marrub--** [comment]
NEVERMIND @DavidPH IS A MEGIT AND STILL HAS MORE WORDS TO EMIT

**Comment by DavidPH** [comment]
I know how I am going to do a non-intrusive stack trace capability, which is probably the core of a lot of debugging needs. But what else do we need? Keep in mind that debugging features need to be categorized by whether or not they degrade performance and whether they can be toggled during engine startup or have to be toggled as a compile-time option. Highest priority should be given to debug capabilities that are non-invasive so they can always be present. Secondary priority to features which would need a command line switch. And "hey it would be cool" priority to things which would require a compile-time configuration.

The most important goal of any debugging capability is that normal builds with default command line options should not have performance degraded for working code.

**Comment by marrub--** [comment]
Indeed.
Stack trace, memory dumping (or printing from a specific address onward), breakpoints, assembly view and perhaps a stack view are all I can really think of.
The latter two would be some horrifying magic done at breakpoints/assertions, memory dumping/printing would be obvious.

**Comment by marrub--** [comment]
There's debug stuff in the engine now, and more being added, so this should be closed.

**Comment by DavidPH** [comment]
I would like to keep this open until I add the bytecode extension to track origins, since that is an actual structural change. `DGE_DebugDataStk` and `DGE_DebugLocReg` are nice for finding compiler issues, but real bugs need functional stack traces.

**Comment by marrub--** [comment]
test comment
