### ISSUE TITLE
More compressed data stream formats

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#28]
Considering adding LZMA and bzip2 compression streams, as well as .7z, .xz, and .bz2 format support.

**Comment by marrub--** [comment]
Should also consider PPMd.

**Comment by Kyle873** [comment]
Supporting 7z would be great, but can we reduce the load times to the point where it isn't slow as all hell?

**Comment by marrub--** [comment]
Yes. Also, I've decided we will only need to support 7z/PPMd and Bzip2 (the compression format, not the file format) in excess.

**Comment by Kyle873** [comment]
Those should be enough to handle all the different data compression situations that one would need, honestly.

**Comment by marrub--** [comment]
This has proven to be overly complicated and not worth doing, so I'm closing this.
I still want to implement BZip2, but it will only be necessary if we add some really complex networking shit that requires giving the user mod files from a server.
