### ISSUE TITLE
Replace NativeLoader pattern

### ISSUE THREAD

**Issue by DavidPH** [Team-Doominati/Doominati#36]
Needing to use NativeLoader stub functions to get natives to actually get added defeats the entire purpose of distributed definitions. It is less of a concern in Code itself, which can reasonably deal with its own quirks, but it is unacceptable to need this in other modules.

Unfortunately, just making the NativeAdder objects not static is not enough, so some other solution needs to be found.

**Comment by marrub--** [comment]
well that's resolved now I guess ;_;
