### ISSUE TITLE
Source tree reorganization

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#38]
is ugle

**Comment by Kyle873** [comment]
Also renaming Game to either Sim or GameSim or some other name that makes it more clear what that subsystem is doing.

**Comment by marrub--** [comment]
I think we've concluded that it should be Game, but I do want to either move the event system to a new module or one that makes more sense than Game, maybe.

**Comment by DavidPH** [comment]
The problem with the event handling is that it makes sense for the input-related events to be handled in Game, but not other ones. Perhaps we need to do a two-stage event handling so we take SDL (or whatever backend) events and repackage them into module-specific pipes.

Other than that, I forget what source tree reorganization you wanted to do, so please elaborate.

**Comment by marrub--** [comment]
Oh, yeah, I just wanted to move the source code into a `source` folder or wherever, but I'm starting to find that it probably wouldn't be necessary.

The problem with events is that they have to be generalized if you don't want to intermingle modules in a rather horrible fashion, so having it just be a general event handler in Game should be fine.
