### ISSUE TITLE
Compressed format support for FS

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#4]
Will need to be done after PNG support, since that includes implementing DEFLATE and the zlib format.

**Comment by marrub--** [comment]
Done with that, David is considering adding PKZIP support to FS now.
Need to restructure the header loading in Zip or just remove it. zlib header loading is useless.
We should consider what PKZIP features we should support, ie. encryption, split file support, self-extracting MZ executable support, et al.

**Comment by DavidPH** [comment]
How about the feature where people combine multiple uncompressed files into a compressed archive and stop asking for weird things they don't need.

**Comment by marrub--** [comment]
That's fair. And sane.

**Comment by DavidPH** [comment]
And now done.
