### ISSUE TITLE
AI and pathfinding

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#46]
This depends mainly on what spatial information the engine has (as opposed to what scripts have) -- whichever one has more info should be doing this.

**Comment by DavidPH** [comment]
Scripts should handle it. It is really not that hard to imagine script-defined circumstances that AI (or pathfinding, even) would need to know about. Whereas game state should almost always be exposed to scripts.

**Comment by marrub--** [comment]
Yeah, it would have to be done entirely in scripts anyway because lodging AI into the engine would be reeeally awkward.
