### ISSUE TITLE
Thinker member access in scripts

### ISSUE THREAD

**Issue by DavidPH** [Team-Doominati/Doominati#48]
There needs to be a way to access Thinker members from scripts by ThinkerID, obviously. But it needs to be fast and (reasonably) robust. Doing a name-based lookup at runtime is right out. Most likely there will be a loader lookup that translates to an index. This index can either be an enumeration (safer) or an object offset (faster). That does leave the question of whether or not to split the API by type. For natives, the obvious answer is yes, as otherwise it would require very strange hacks to access non-integer members. Internally, it's hard to say. If the API is not split, then the Thinker member functions presumably just convert to `Code::Word`. Accessing a member by the wrong type will give a malformed result. If the API is split, then there is an actual question about how to handle type mismatch. Either it fails to find the member (and thus returns whatever that value is (probably 0)) or it converts to the desired type. I am most inclined to have a non-split internal API.

There is also the question of storing extension members. I am currently leaning towards allocating them along with the owning object and accessing them by ThinkerID and index. This does require the number of extension members to be committed to at object creation, but I think that is reasonable. There will likely be two kinds of extension members. Global ones, which are registered during engine loading (either in codedefs or gamedefs) and are always added to any allocation of the relevant Thinker type. (And are also referenced by name during loading.) And instance ones, which would be specified as a count passed to the creation native. Instance members would be allocated after global members, and so would be indexed as an offset of the combined size of global members, also available as a loader symbol.

Putting this up, because some of these affect how the base Thinker class gets designed, and in case anyone has other ideas on the subject.

**Comment by marrub--** [comment]
:+1:

**Comment by DavidPH** [comment]
So, this became Object Members, but yes. Extension members exist (including instance extension members), but there's no proper API for them, yet.

**Comment by DavidPH** [comment]
There are now both Global Extension Members and Instance Extension Members that can be actually defined and used by real scripts, so this should be all done.
