### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by DavidPH** [Team-Doominati/Doominati#51]
`Thinker` is a game object that changes over time. `Entity` is a `Thinker` that reacts to external stimuli at a higher level than basic physics. Given the latter's obvious core usefulness to gameplay, it needs to come into existence. As discussed elsewhere, the class hierarchy will be `Thinker` -> `PointThinker` -> `RenderThinker` -> `PhysicsThinker` -> `Entity`. While the most basic parts of defining these classes should be simple, now is probably the time to start thinking about how `Entity` is going to interact with the environment (including over time).

**Comment by DavidPH** [comment]
`Entity` exists, and at this point it seems that its interactions with the environment will be pure scripting for the foreseeable future. Since that leaves any shortcomings as separate issues, is there anything left to discuss here?

**Comment by Kyle873** [comment]
I don't think so. I think we're safe to close this unless something else comes up.
