### ISSUE TITLE
Particle system natives

### ISSUE THREAD

**Issue by marrub--** [Team-Doominati/Doominati#9]
need to try and optimize via SSE as per #8 and test with practical effects

**Comment by marrub--** [comment]
Nevermind optimizing via SSE. Eigen's vectors are horrendeous terror that's impossible to use. Still need to test with some actual effects, but I'll have to do that after implementing PNG.

**Comment by marrub--** [comment]
Side note: Tested with a ridiculous amount of particles per tic, and it is.. more than fast enough, anyway.

**Comment by Kyle873** [comment]
Practical effects would include some base implementations of things such as fire, smoke, rain, snow, flares, rings, etc. Maybe also some sort of special implementation for sprite after-images? (i.e. Castlevania SOTN, many fighters, etc)

**Comment by marrub--** [comment]
Need to make natives for this and probably rewrite the code a bit. Otherwise it's still basically done.

**Comment by marrub--** [comment]
`ParticleSystem` (which will be `ParticleSys`) has been decoupled from GL, so it'll be turned into an `Object` that can be created from scripts. From there, you'll be able to add particles to it with a native like:
```c
void DGE_ParticleSys_Add(unsigned prs, DGE_Particle *prt);
```

**Comment by Kyle873** [comment]
I can't remember what all properties and modifiers our particle systems currently have, but I imagine a 1:1 mimicking of their general member structure into exposed setter functions would be a good start in terms of natives.

**Comment by marrub--** [comment]
Yeah, it'll literally just be the structure as it is in-engine (sans the next pointer.) You just hand it the struct and it mirrors that information into a new particle.

**Comment by marrub--** [comment]
Done in 0d06ccb.
